### ISSUE TITLE
Subscriptions and SubscriptionsOptions DB Empty

### ISSUE THREAD

**Issue by ObinnaAka** [michalkvasnicak/aws-lambda-graphql#95] opened 2020-07-20 22:29 UTC
Hello,

I've been trying over the past few days to get subscriptions working with my application. I set things up like you did in the example and I used Serverless to deploy it to AWS. However, I can't get subscriptions either on the website or testing with playground.

****
In the dev tools, I can see that it is connecting to the webSocket, and receiving an acknowledgement.

![image](https://user-images.githubusercontent.com/33449354/87991275-6de27f00-caab-11ea-83d5-e80b0642b296.png)

And everything else seems to work. The mutations and the queries.

In DynamoDB, all the tables are being created I believe

![image](https://user-images.githubusercontent.com/33449354/87991524-f95c1000-caab-11ea-884f-40b3aeb20e94.png)

But I noticed that the subscriptions table is always empty. There is some activity when it comes to reading but none when it comes to writing.

![image](https://user-images.githubusercontent.com/33449354/87991675-493ad700-caac-11ea-873a-d0c880cedd5f.png)

I'm attaching my serverless.yml, graphql.js (index.js) and also the subscription resolvers.

****
**Serverless.yml**
```
provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1 # NOTE: change with your preferred region
  memorySize: 256

  iamRoleStatements:
    - Effect: Allow
      Action:
        - execute-api:ManageConnections
      Resource: "arn:aws:execute-api:*:*:*/dev/POST/@connections/*"
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: !GetAtt ConnectionsDynamoDBTable.Arn
    - Effect: Allow
      Action:
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource: !GetAtt EventsDynamoDBTable.StreamArn
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: !GetAtt EventsDynamoDBTable.Arn
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource: !GetAtt SubscriptionsDynamoDBTable.Arn
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: !GetAtt SubscriptionOperationsDynamoDBTable.Arn

functions:
  wsHandler:
    handler: graphql.handleWebSocket
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
  eventProcessorHandler:
    handler: graphql.handleEvents
    events:
      - stream:
          enabled: true
          type: dynamodb
          arn:
            Fn::GetAtt: [EventsDynamoDBTable, StreamArn]
  # this one is optional (if you want to support HTTP)
  httpHandler:
    handler: graphql.handleHTTP
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /graphiql
          method: any
          cors: true

resources:
  Resources:
    ConnectionsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # see DynamoDBConnectionManager
        TableName: Connections
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          # connection id
          - AttributeName: id
            KeyType: HASH
        # This one is optional (all connections have 2 hours of lifetime in ttl field but enabling TTL is up to you)
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    SubscriptionsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # see DynamoDBSubscriptionManager
        TableName: Subscriptions
        AttributeDefinitions:
          - AttributeName: event
            AttributeType: S
          - AttributeName: subscriptionId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: event
            KeyType: HASH
          - AttributeName: subscriptionId
            KeyType: RANGE
        # This one is optional (all subscriptions have 2 hours of lifetime in ttl field but enabling TTL is up to you)
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    SubscriptionOperationsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # see DynamoDBSubscriptionManager
        TableName: SubscriptionOperations
        AttributeDefinitions:
          - AttributeName: subscriptionId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: subscriptionId
            KeyType: HASH
        # This one is optional (all subscription operations have 2 hours of lifetime in ttl field but enabling TTL is up to you)
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    EventsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # see DynamoDBEventStore
        TableName: Events
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        # see ISubscriptionEvent
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        # This one is optional (all events have 2 hours of lifetime in ttl field but enabling TTL is up to you)
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
```

****

**graphql.js**
```
const { tradeTokenForMember, authenticated } = require("./middleware/is-auth");
const {
	DynamoDBConnectionManager,
	DynamoDBEventProcessor,
	DynamoDBEventStore,
	DynamoDBSubscriptionManager,
	PubSub,
	Server,
} = require("aws-lambda-graphql");

const typeDefs = require("./graphql/schema/index");
const resolvers = require("./graphql/resolvers/index");

const eventStore = new DynamoDBEventStore();
const eventProcessor = new DynamoDBEventProcessor();
const subscriptionManager = new DynamoDBSubscriptionManager();
const connectionManager = new DynamoDBConnectionManager({
	subscriptionManager,
});
const pubsub = new PubSub({ eventStore });

const server = new Server({
	// accepts all the apollo-server-lambda options and adds few extra options
	// provided by this package
	connectionManager,
	eventProcessor,
	resolvers,
	subscriptionManager,
	typeDefs,
	playground: {
		endpoint:
			"******/dev/graphiql",
		subscriptionEndpoint:
			"******/dev",
	},
	context: async ({ event, lambdaContext }) => {
		let token = null;
		let currentMember = null;
		console.log("Set token for context");
		try {
			token = event.headers.Authorization;
			if (token) {
				currentMember = await tradeTokenForMember(token);
			}
		} catch (err) {
			console.warn(`Unable to authenticate using auth token: ${token}`);
		}
		return {
			token,
			currentMember,
			pubsub,
			headers: event.headers,
			event,
			lambdaContext,
		};
	},
});

module.exports.handleWebSocket = server.createWebSocketHandler();
module.exports.handleHTTP = server.createHttpHandler({
	cors: {
		origin: "*",
		credentials: false,
	},
});
// this creates dynamodb event handler so we can send messages to subscribed clients
module.exports.handleEvents = server.createEventHandler();
```
****
**resolver**

```

	Subscription: {
		onNewRequest: {
			//! Will need WithFilter here to filter for only "Processing transactions"
			resolve: (rootValue) => {
				return rootValue;
			},
			subscribe: (rootValue, args, ctx, info) => {
				ctx.pubsub.subscribe(TRANSACTION_SUBSCRIPTION)(
					rootValue,
					args,
					ctx,
					info
				);
			},
```

****

Please let me know if you need more info

P.s. I'm a self proclaimed noob so please let me know if my logic is wrong

**Comment by michalkvasnicak** [comment] 2020-07-21 06:34
@ObinnaAka it seems that your client is subscribing and unsubscribing over and over again (screenshot # 1). When `stop` operation is sent, the subscription is deleted. So I'd check the client side because server code seems to be OK.

**Comment by michalkvasnicak** [comment] 2020-07-21 06:40
Please in your resolver, return the result of `subscribe` call.

```
	Subscription: {
		onNewRequest: {
			//! Will need WithFilter here to filter for only "Processing transactions"
			resolve: (rootValue) => {
				return rootValue;
			},
			subscribe: (rootValue, args, ctx, info) => {
				return ctx.pubsub.subscribe(TRANSACTION_SUBSCRIPTION)(
					rootValue,
					args,
					ctx,
					info
				);
			},
```

**Comment by ObinnaAka** [comment] 2020-07-21 18:25
Hello @michalkvasnicak  thank you for the help! The subscribing and unsubscribing was on purpose, I was just testing out the connection. When I leave it on the page, it remains consistently connected, but there's still no data coming from the subscription.

And thank you for your suggestion. I tried using that but unfortunately it still doesn't work. And the Subscriptions table still remains empty even on a consistent connection

**Comment by michalkvasnicak** [comment] 2020-07-22 06:17
Ok I found a problem, you need to pass `SubscriptionManager` to `ConnectionManager` in `subscriptions` option (https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/DynamoDBConnectionManager.ts#L38). 

Just change:

```
const connectionManager = new DynamoDBConnectionManager({
	subscriptionManager,
});
```

to

```
const connectionManager = new DynamoDBConnectionManager({
	subscriptions: subscriptionManager,
});
```

I think you should have errors in cloud watch logs for your function.

**Comment by ObinnaAka** [comment] 2020-07-23 03:07
Thanks again @michalkvasnicak  but unfortunately it didn't work. You were right though, I occasionally get an error in my cloudwatch log. 

![image](https://user-images.githubusercontent.com/33449354/88248312-5d2a3880-cc66-11ea-8997-7084705a32da.png)

I did some tracing and logging to see if some functions were being called at all and it seems like the subscription is not executing.

None of these logged (although I'm not sure that they're supposed to)
****
![image](https://user-images.githubusercontent.com/33449354/88248400-b2664a00-cc66-11ea-9f4c-6d198ce20d5d.png)

But also, none of these logged either.
****
![image](https://user-images.githubusercontent.com/33449354/88248502-0113e400-cc67-11ea-988c-387e2f3ff8a2.png)


I the think the typeError might've come from me working with GraphiQL and not adding "OperationName = subscription" to the headers.

Thanks again for your help!

**Comment by michalkvasnicak** [comment] 2020-07-23 06:23
How do you test it ? Could you please explain client side steps you do in order to test your server implementation? Because I don't see any problem with the server code you provided.

**Comment by michalkvasnicak** [comment] 2020-07-23 06:28
Error in your logs can be caused by this line https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/execute.ts#L97 which means that operation you sent is malformed. 

But I'd need more information. Is it caused by sending a mutation or does it happen when you're trying subscribe?

**Comment by ObinnaAka** [comment] 2020-07-25 04:23
Hello @michalkvasnicak , unfortunately it still isn't working. Here is a screenshot for my frontend implementation 
****
Here is the index.js for the React App
```
import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
import App from "./App";
import * as serviceWorker from "./serviceWorker";

import { split } from "apollo-link";
import { ApolloClient } from "apollo-client";
import { createHttpLink } from "apollo-link-http";
import { setContext } from "apollo-link-context";
import { InMemoryCache } from "apollo-cache-inmemory";
import { ApolloProvider, withApollo } from "react-apollo";
import { WebSocketLink } from "apollo-link-ws";
import { getMainDefinition } from "apollo-utilities";
import { SubscriptionClient } from "subscriptions-transport-ws";

// ------------------------------------------------------------------
// * References
// https://github.com/michalkvasnicak/aws-lambda-graphql
// https://stackoverflow.com/questions/61690378/aws-amplify-react-app-deploy-error-too-many-redirect-or-aws-build-settings
// ------------------------------------------------------------------

const wsClient = new SubscriptionClient(
	"wss://skaq2dxiil.execute-api.us-east-1.amazonaws.com/dev/", // please provide the uri of the api gateway v2 endpoint
	{ lazy: true, reconnect: true },
	null,
	[]
);

const httpLink = createHttpLink({
	uri: "https://s6rbb7i554.execute-api.us-east-1.amazonaws.com/dev/",
});

const wsLink = new WebSocketLink(wsClient);

const authLink = setContext((_, { headers }) => {
	// get the authentication token from local storage if it exists
	const token = localStorage.getItem("token");
	// return the headers to the context so httpLink can read them
	return {
		headers: {
			...headers,
			authorization: token ? `Bearer ${token}` : "",
		},
	};
});

const link = split(
	({ query }) => {
		const { kind, operation } = getMainDefinition(query);
		return kind === "OperationDefinition" && operation === "subscription";
	},
	wsLink,
	httpLink
);

const client = new ApolloClient({
	link: authLink.concat(link),
	credentials: "same-origin",
	cache: new InMemoryCache(),
});

const AppWithClient = withApollo(App);

```

****
Here is the subscription query
```
const SIGNED_IN_STUDENTS_SUBSCRIPTION = gql`
	subscription {
		onNewStudent {
			_id
			transactionType
			member {
				firstName
				lastName
				itemRecord {
					name
				}
				workstation {
					name
				}
			}
			comment
			updatedAt
		}
	}
`;
```
****
Here is the useSubscription
```
const SignedInStudents = (Apollo) => {
	const [students, setStudents] = useState([]);

	useSubscription(SIGNED_IN_STUDENTS_SUBSCRIPTION, {
		onSubscriptionData: ({ subscriptionData }) => {
			console.log(subscriptionData);
			if (subscriptionData) {
				let newStudent = [subscriptionData.data.onNewStudent.member];
				let newStudents = newStudent.concat(students);
				setStudents(newStudents);
			} else {
				return <div className="page">No new students</div>;
			}
		},
	});
```

**Comment by michalkvasnicak** [comment] 2020-07-25 06:19
What version of `aws-lambda-graphql` do you have? Can you upgrade to `1.0.0-alpha.13` because as I wrote above, versions `alpha.10-12` are deprecated because of an error in headers processing. 

If that won't help, can you provide a minimal project repository? But I don't think this is a problem with `aws-lambda-graphql`. There must be something else going on in your code.

I need to see how you publish events, and if you can, provide CloudWatch logs of websocket lambda handler after client subscribes, because if you don't have subscriptions in your table, an error should occur on subscription.

**Comment by ObinnaAka** [comment] 2020-07-25 23:03
Yes, I believe I upgraded to 1.0.0-alpha.13 before testing it again. I invited you to the repository, and the branch name is `serverless`. The resolvers are under `server/graphql/resolvers`

 And these are the cloud watch logs:

[log-events-viewer-result.xlsx](https://github.com/michalkvasnicak/aws-lambda-graphql/files/4976863/log-events-viewer-result.xlsx)

The operations header error does occur here.

Thank you again!

**Comment by michalkvasnicak** [comment] 2020-07-27 07:11
I haven't found any error in your repository in server package. I haven't tested it because it relies on Mongo so it's not really something I can just quickly run. 

The error logged in your logs can be caused by invalid parsing of GraphQL operation so it would be helpful to see a JSON operation that is being sent when the client is subscribing to some subscription. The problem happens in `execute` function which is called in web socket handler created by `server.createWebSocketHandler()`. If you can send a `mutation` or `query` and get correct result then the problem is in `subscription` operation. So I'd try sending some test query and mutation over websocket if the server returns correct response.

But as I said, I don't think this is a problem with `aws-lambda-graphql` library. So I'm closing this unless you provide me with some minimum repository that I can run without any problem.

**Closed by michalkvasnicak** 2020-07-27 07:11 UTC
