### ISSUE TITLE
Multiple subscriptions

### ISSUE THREAD

**Issue by clmntrss** [michalkvasnicak/aws-lambda-graphql#114] opened 2020-09-03 09:19 UTC
Hello again, I would like to know if it is possible to create several subscriptions in order to subscribe to several types of events. 

For example :

- Client creating 2 subscriptions on events "A1" and "A2".
- Server return events with type "A1" and "A2". 

Currently, it is not possible to pass array with several entries in the initial subscriptions : 

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/47cd7fe2cfdd5fd65c5bdadfeddf011307cb9ee0/packages/aws-lambda-graphql/src/DynamoDBSubscriptionManager.ts#L165

Is this a limitation of AWS/DynamoDB or do you think the library can be modified to allow it?

@ebarault

**Comment by michalkvasnicak** [comment] 2020-09-03 09:40
I'm not sure now why I did it that way but the problem seems to be with subscription operations table where we have only `subscriptionId` as `HASH`:

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/chat-example-server/serverless.yml#L145

So we have a subscription table that holds subscriptions' id by events:

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/chat-example-server/serverless.yml#L125

But we can't store all events in `SubscriptionOperationsDynamoDBTable`  because we don't have `RANGE` key for `event`. So I think it should be enough to add the `RANGE` key for `event` on `SubscriptionOperationsDynamoDBTable ` and then insert all events. So basically it looks like inverse `SubscriptionsDynamoDBTable` because it uses `event` as `HASH` and `subscriptionId` as `RANGE`.

**Comment by michalkvasnicak** [comment] 2020-09-03 09:43
Do you think using an index would be easier so we can get rid of the `SubscriptionOperationsDynamoDBTable` table or is there any limitation?

**Comment by ebarault** [comment] 2020-09-03 10:03
Hi @michalkvasnicak,

Thanks for your reactivity on this.

I don't have a precise enough understanding on how you use the `SubscriptionOperationsDynamoDBTable` table to properly answer your question, but I can describe the way we understood it'd be running and how we could interface with it.

We have an external system that looks the content of the `SubscriptionsDynamoDBTable` table to trigger some external decisions (this system cannot directly interact with the graphql API so it has to look directly inside the table)

This system expects one record in the `SubscriptionsDynamoDBTable` table for one subscription.
We do not deal with `SubscriptionOperationsDynamoDBTable` table.

We basically made the assumption that it would run this way:
- front subscribes to multiple events
- back creates one record in the `SubscriptionsDynamoDBTable` per table

Whether it would result in opening multiple websocket connections (one per event), or multiplex all the data in a single websocket connection was unclear.

cc: @clmntrss

**Comment by michalkvasnicak** [comment] 2020-09-03 10:19
@ebarault `SubscriptionOperationsDynamoDBTable` is used to find an `event` by `subscriptionId` which consists of `connectionId` and `operationId` and this is a problem because it allows us to store only on event per operation. 

In order to allow to subscribe to multiple events in one subscription resolver e.g. `pubSub.subscribe(['A1', 'A2'])` we need to add a `RANGE` key on `event` column in `SubscriptionOperationsDynamoDBTable` so we can identify all events in given GraphQL subscription operation and unsubscribe them correctly. But in this case we already have all the required information in  `SubscriptionsDynamoDBTable` but there is `event` as `HASH` and `subscriptionId` as `RANGE`.

So to allow to subscribe to more than 1 event in any subscription resolver we need to either:

* remove `SubscriptionOperationsDynamoDBTable` and establish an index on `SubscriptionsDynamoDBTable` which changes `event` to `RANGE` and `subscriptionId` to `HASH`

or 

* make `event` a `RANGE` in  `SubscriptionOperationsDynamoDBTable` because we already store it:

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/e3cbe5ee88c0d0cf723260d232dcacc260a8ffec/packages/aws-lambda-graphql/src/DynamoDBSubscriptionManager.ts#L191-L202

**Comment by michalkvasnicak** [comment] 2020-09-03 10:34
> Whether it would result in opening multiple websocket connections (one per event), or multiplex all the data in a single websocket connection was unclear.

@ebarault if you have only one GraphQL client in your application then you are subscribing over the same connection with the same `connectionId` but the operations has unique `operationId`. We use this `operationId` and `connectionId` to create `subscriptionId` so we are already able to store all the events we subscribe to in the `SubscriptionsDynamoDBTable`. But the problem is that `SubscriptionOperationsDynamoDBTable` doesn't allow us to do that. 

So your system that interacts with `SubscriptionsDynamoDBTable` and expects only one event per `subscriptionId` can break if we allow to subscribe to multiple events in one GraphQL operation. But in my opinion it should be possible to subscribe to more than one event in pubSub because you can have 1 GraphQL subscription that reacts to multiple events in your system.

**Comment by ebarault** [comment] 2020-09-03 10:43
@michalkvasnicak 
I don't expect our external system to break as long as we write one record for each subscribed event in the `SubscriptionsDynamoDBTable` table. This is currently in dev phase, so schemas can change :-)

As for the choice between the 2 scenarios, I now understand, thank you for providing the details. So, as I thought, the `SubscriptionOperationsDynamoDBTable` just has a technical purpose in the whole solution. I'd personally choose to simplify the data model and get rid of it if this can be supported by enriching the `SubscriptionsDynamoDBTable` table and we don't identify any side effect.

Where does you preference go ?

PS. Using one single connection for multiple subscriptions is the way to go for sure.

**Comment by michalkvasnicak** [comment] 2020-09-03 11:33
I'm not an expert on DynamoDB but we can replace `SubscriptionOperationsDynamoDBTable` with global index over `SubscriptionsDynamoDBTable`. Only drawback I can think of is eventual consistency and I don't know what implications it'd have during unsubscribing because we need to know which events are subscribed to in given subscription.

Maybe there is a third way to use single table design so we'd use one table only without any index.

**Comment by ebarault** [comment] 2020-09-03 16:05
@michalkvasnicak, could you precise your fears regarding eventual consistency, and most of all the difference you see from having one or two tables?

Regarding the 3rd scenario, with a single table design: what other tables would be aggregated in this single table ?

**Comment by michalkvasnicak** [comment] 2020-09-04 06:37
@ebarault it could cause `SubscriptionsDynamoDBTable` to contain dead subscriptions (because we unsubscribed sooner than the operations have been written) or fail when client is unsubscribing and the operation is not propagated in index. But I think those could be just edge cases (as I said I'm not an expert so I don't really know how DynamoDB Global Indexes behave in real world scenario).

With single table approach I would combine `SubscriptionsDynamoDBTable` and `SubscriptionOperationsDynamoDBTable` to one table that stores 2 types of records:

1. event to subscriptions as `event: HASH`, `subscriptionId: RANGE`
2. subscriptions to events as `subscriptionId: RANGE`, `event: HASH`

Basically it would have new names for keys, `PK: HASH` and `SK: RANGE` and store records prefixed with their type so we would have:

1. `EVENT:{name}` as `PK` and `subscriptionId` as `SK`
2. `SUBSCRIPTION:{subscriptionId}` as `PK` and `event` as `SK`

With this design we can find all subscribers to an event and all subscribed events in a subscription in one table.

I think that even `ConnectionsDynamoDBTable` can be moved to single table design too:

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/e3cbe5ee88c0d0cf723260d232dcacc260a8ffec/packages/chat-example-server/serverless.yml#L95

This is a breaking change but we're in alpha version so users can always lock to the version they use instead of updating straight away.

**Comment by michalkvasnicak** [comment] 2020-09-04 06:38
Maybe it could be introduced as a new package just with new DynamoDB code that uses new table design. So this way we won't introduce a breaking change in a lib but you will have a choice to use different adapters.

**Comment by ebarault** [comment] 2020-09-04 08:00
Ah I see what you have in mind.

But our external system expects to have only one type of record for the subscriptions (one record per subscribed event), so given the above discussion, i'd stick to the tables as they are right now, adding the Range key in the `SubscriptionOperationsDynamoDB` table as you suggested in:

> "So I think it should be enough to add the RANGE key for event on SubscriptionOperationsDynamoDB Table and then insert all events"

And one in all, it won't be a breaking change. What do you think ?

**Comment by michalkvasnicak** [comment] 2020-09-04 08:12
@ebarault yes I think this is the easiest solution. For single table approach I'd rather create a new package.

**Comment by michalkvasnicak** [comment] 2020-09-04 08:29
Even the approach with `RANGE` key is breaking change because to delete a record you need to address it with `HASH + RANGE` key but this can be solved at library level.

**Comment by ebarault** [comment] 2020-09-07 08:08
Hi @michalkvasnicak 
How do you see the next move on this feature, and how can we help? We can definitely test and report (we are running our app in a full AWS context) at least.

**Comment by michalkvasnicak** [comment] 2020-09-07 09:12
@ebarault I don't have much time this week so if have some spare time to work on this I'd appreciate it. We have 2 ways how to implement this without breaking change.

## 1. DynamoDBSubscriptionManager option

Add an option to `DynamoDBSubscriptionManagerOptions` saying whether we have `RANGE` on `event` or not. This way we  default to keep it compatible with current implementation or use new logic for `subscribe/unsubscribe*`.

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/DynamoDBSubscriptionManager.ts#L30

## 2. New DynamoDBSubscriptionManager

We can offer another implementation of `DynamoDBSubscriptionManager` that allows us to subscribe to multiple events. This is approach is more error resistant in my opinion because we'd document it with `RANGE` key as requirement in mind.

In this case we'd need to add comments to `serverless/cloudformation` templates saying that you need `event` `RANGE` key in order for this to work. The same applies for option 1.

I'd take consider second approach as better way to do this. Because I think it's easier to document and test.

**Comment by michalkvasnicak** [comment] 2020-09-07 09:14
Later in version stable 1.0 version I'd get rid of the old code and use only `DynamoDBSubscriptionManager` that supports multiple events per subscription.

**Comment by ebarault** [comment] 2020-09-07 09:48
@michalkvasnicak ok, how do you see the way to introduce another implementation of `DynamoDBSubscriptionManager`? 
- a feature flag to select the preferred one ? (defaulting to the current one?) then what name should we have for this flag + new class
- just offering the new implementation, the older new being available in older releases ?

**Comment by michalkvasnicak** [comment] 2020-09-07 09:52
@ebarault I thought to offer both implementations but the new one needs a new name at least for now until 1.0 is released. In 1.0 will new subscription manager be named `DynamoDBSubscriptionManager` and the old one will be deleted.

So basically we should a new class but I don't know how to name it. Any ideas? I don't want to use feature flags because in that case we need to document them.

**Comment by ebarault** [comment] 2020-09-07 09:56
@michalkvasnicak hmm ok but what to you have in mind for selecting which implementation the backend should use? by detecting at dynamodb table level whether the event key is set as a Range key in the operations table ?

**Comment by michalkvasnicak** [comment] 2020-09-07 10:13
@ebarault I thought we'll have another class you will import and use. For example `DynamoDBRangedSubscriptionManager` (of course this name is made up). So in your codebase you'd just import different class instead of `DynamoDBSubscriptionManager` in order to allow for multiple events per subscription.

**Comment by ebarault** [comment] 2020-09-07 11:30
ahh yes of course. fine by me, this will be easy to test along the way.

**Comment by michalkvasnicak** [comment] 2020-09-07 11:54
@ebarault would you like to work on this?

**Comment by ebarault** [comment] 2020-09-07 11:56
@clmntrss will work on the implementation, and i'll set up a new aws deployment to test it

**Comment by michalkvasnicak** [comment] 2020-09-07 11:57
@ebarault great! Thank you. @clmntrss I'll assign this to you 🙂

**Closed** 2021-01-18 15:11 UTC
Labels: enhancement
