### ISSUE TITLE
Error when running example app

### ISSUE THREAD

**Issue by caseyhoward** [michalkvasnicak/aws-lambda-graphql#37] opened 2019-11-12 20:28 UTC
I've been trying to get this library working on a project and am having no luck. So I tried just getting the examples in the project to work. I followed the directions in each of the repos however it doesn't work. I deployed the server to wss://f6aifsw9g7.execute-api.us-east-1.amazonaws.com/dev and I get an error in the client when subscribing: "Prohibited connection". I have a screenshot for when it works on https://chat-example-app.netlify.com/ and one of it not working when I use my own deployment.

Working
![good](https://user-images.githubusercontent.com/16295/68707816-55e35480-0547-11ea-9198-c46720c81230.png)

Not working
![bad](https://user-images.githubusercontent.com/16295/68707821-58de4500-0547-11ea-9ed5-9e7095fc9bcc.png)

Has anyone seen this before and know how to fix it or how I can troubleshoot it? I'm kind of stuck right now. I don't see any errors in the AWS logs. Thanks!

**Comment by michalkvasnicak** [comment] 2019-11-13 07:55
@caseyhoward yes it's caused by #33. Basically what's happening is that `onConnect` phase is running and during that phase the connection is not initialised, so when you send `subscriptions` during that phase to the server it'll reject them with prohibited connection message.

I need to fix that so the connection is initialised if you don't have `onConnect` custom logic.

**Comment by caseyhoward** [comment] 2019-11-13 17:30
Ok, the only thing I don't understand is why the chat-example-app.netlify.com version of the app works. Is it a timing issue? Is there anything I can do to get it working right now? Delay sending the subscription or something? Thanks.

**Comment by michalkvasnicak** [comment] 2019-11-14 08:06
@caseyhoward the chat app is deployed with old version, I just need to redeploy it. 

Otherwise Prohibited connection is caused by the following problem:

Apollo's subscription-transport-ws is not waiting for CONNECTION_ACK so basically when you connect to the server and you have some authentication going in `onConnect` handler, then when you try to subscribe in the meantime (until the `onConnect` is resolved successfully) you'll get error. So basically you should send graphql operations after some time (basically after `onConnect` is resolved), but you don't have a way how to get the information if it's resolved or not. So you can send them let's say after 1 second or I need to implement #33  which will delay the operation on the server for some time until the `onConnect` is resolved.

I don't have time at the moment to fix that but maybe I'll make some time to fix it until weekend and if not, I'll fix that over the weekend.

**Comment by michalkvasnicak** [comment] 2019-11-17 09:24
@caseyhoward I introduced new optional setting to `createWsHandler` that controls how the handler should behave if connection is not initialised during the GraphQL operation (`onConnect` is not resolved yet).

Please see #40 

It's released as `0.11.0`. Also I redeployed the example app for new version.

**Closed by michalkvasnicak** 2019-11-17 09:24 UTC
Labels: duplicate

**Comment by IslamWahid** [comment] 2020-06-30 10:35
@michalkvasnicak is that still relevant I'm getting the same issue with `^1.0.0-alpha.4`

**Comment by michalkvasnicak** [comment] 2020-06-30 10:39
@IslamWahid it depends on how the `waitForInitialization` is set up. If your `onConnect` takes too long it can cause the `Prohibited connection` problem.

**Comment by IslamWahid** [comment] 2020-06-30 11:18
thanks @michalkvasnicak, I would try to set the `waitForInitialization` and see how would it behave.
I'm just doing the JWT authentication in the `onConnect` but it seems to be not the right place for it. I think it should be moved to the context.
what do you think about that?

**Comment by michalkvasnicak** [comment] 2020-06-30 11:27
@michalkvasnicak I store JWT token in context and verify it during context creation. But also you can verify it on demand in protected resolvers, so the answer is as with everything in engineering "it depends" 😄 

But maybe just try to tweak `waitForInitialization` if you need to check it only on connect. Now it uses 10 retries with 50ms timeouts so you have around 500ms to resolve `onConnect`.

**Comment by IslamWahid** [comment] 2020-06-30 11:31
@michalkvasnicak thanks for your help :D. that sounds good I think `waitForInitialization` is gonna be the solution for the main issue then it doesn't matter so much about the authentication.

**Comment by IslamWahid** [comment] 2020-06-30 15:19
@michalkvasnicak but I have a question why are you saving the connection in dynamo without waiting for the `onConnect`, when I saw the `onConnect` I thought I can do the validation on this place to make sure that all the connections are done with a valid token. but it ended up with saving all the connection either it's authenticated or not and now I've to get rid of those non-authenticated connections.

**Comment by IslamWahid** [comment] 2020-06-30 15:50
@michalkvasnicak just to understand the whole flow when there's a new connection received by the gateway we get it and we create the record on dynamo for it then `onConnect` is called, but in case that `onConnect` is throwing a validation error we don't delete the record from dynamo we depend only on the `$disconnect` event from the gateway which in my case if the validation is done on the `onConnect` will never happen.
